namespace Atc.CodingRules.Updater.Tests;

/// <summary>
/// Covers the temporary-suppressions header block, written in two places that must agree:
/// the block appended to <c>.editorconfig</c> and the standalone file written when
/// <c>--temporarySuppressionPath</c> is set.
/// </summary>
/// <remarks>
/// Issue #67 asked for the updater version in this block. The culture assertions cover a defect
/// found alongside it: the <c>.editorconfig</c> site formatted the timestamp with the ambient
/// culture, so the committed file differed between developers on different locales.
/// </remarks>
public sealed class SuppressionHeaderTests
{
    private static readonly string WorkingDirectory = Path.Combine(
        Path.GetTempPath(),
        "atc-coding-rules-updater-suppression-header-test");

    private static readonly IList<Tuple<string, List<string>>> Suppressions =
    [
        Tuple.Create("Provider.A", new List<string> { "dotnet_diagnostic.CA1303.severity = suggestion" }),
    ];

    [Fact]
    public async Task EditorConfigBlock_NamesTheUpdaterVersion()
    {
        var content = await WriteEditorConfigBlockAsync(nameof(EditorConfigBlock_NamesTheUpdaterVersion));

        content.Should().Contain("generated by: atc-coding-rules-updater v");
    }

    [Fact]
    public void StandaloneFile_NamesTheUpdaterVersion()
    {
        var actual = ProjectHelper.CreateSuppressionsText(Suppressions);

        actual.Should().Contain("generated by: atc-coding-rules-updater v");
    }

    [Fact]
    public async Task EditorConfigBlock_VersionMatchesTheRunningVersion()
    {
        var content = await WriteEditorConfigBlockAsync(nameof(EditorConfigBlock_VersionMatchesTheRunningVersion));

        content.Should().Contain(CodingRulesUpdaterVersionHelper.GetGeneratedByText());
    }

    [Fact]
    public async Task EditorConfigBlock_TimestampIsCultureInvariant()
    {
        // Without an explicit culture the block picked up the machine's locale, so two developers
        // running the same command committed different text.
        var content = await WithCultureAsync(
            "da-DK",
            () => WriteEditorConfigBlockAsync(nameof(EditorConfigBlock_TimestampIsCultureInvariant)));

        GeneratedTimestampOf(content).Should().NotBeNull();
    }

    [Fact]
    public async Task StandaloneFile_TimestampIsCultureInvariant()
    {
        var actual = await WithCultureAsync(
            "da-DK",
            () => Task.FromResult(ProjectHelper.CreateSuppressionsText(Suppressions)));

        GeneratedTimestampOf(actual).Should().NotBeNull();
    }

    /// <summary>
    /// Returns the timestamp from the header when it is formatted with the English full
    /// date/time pattern, or <c>null</c> when it is not.
    /// </summary>
    private static DateTime? GeneratedTimestampOf(string content)
    {
        var line = content
            .Split(FileHelper.LineBreaks, StringSplitOptions.None)
            .FirstOrDefault(x => x.Contains("generated @", StringComparison.Ordinal)
                                 || x.Contains("ATC temporary suppressions ", StringComparison.Ordinal));

        if (line is null)
        {
            return null;
        }

        // The two sites use different prefixes: "# generated @ <ts>" in the .editorconfig block
        // and "# ATC temporary suppressions <ts>" in the standalone file.
        var atIndex = line.IndexOf('@', StringComparison.Ordinal);
        var value = atIndex >= 0
            ? line[(atIndex + 1)..].Trim()
            : line[(line.IndexOf("suppressions ", StringComparison.Ordinal) + "suppressions ".Length)..].Trim();

        return DateTime.TryParseExact(
            value,
            "F",
            GlobalizationConstants.EnglishCultureInfo,
            DateTimeStyles.None,
            out var parsed)
            ? parsed
            : null;
    }

    private static async Task<T> WithCultureAsync<T>(
        string culture,
        Func<Task<T>> action)
    {
        var original = CultureInfo.CurrentCulture;
        try
        {
            CultureInfo.CurrentCulture = new CultureInfo(culture);
            return await action();
        }
        finally
        {
            CultureInfo.CurrentCulture = original;
        }
    }

    private static async Task<string> WriteEditorConfigBlockAsync(
        string testName)
    {
        var path = Path.Combine(WorkingDirectory, testName);
        if (Directory.Exists(path))
        {
            Directory.Delete(path, recursive: true);
        }

        var directory = Directory.CreateDirectory(path);
        var file = new FileInfo(Path.Combine(directory.FullName, EditorConfigHelper.FileName));
        await File.WriteAllTextAsync(file.FullName, "root = true", TestContext.Current.CancellationToken);

        await EditorConfigHelper.UpdateRootFileAddCustomAtcAutogeneratedRuleSuppressions(directory, Suppressions);

        return await File.ReadAllTextAsync(file.FullName, TestContext.Current.CancellationToken);
    }
}