<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;_PUBLISH_CHROMEDRIVER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atc" Version="3.0.186" />
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atc.CodingRules\Atc.CodingRules.csproj" />
  </ItemGroup>

</Project>
