namespace Atc.CodingRules.Updater;

public static class CodingRulesUpdaterVersionHelper
{
    public static Version? GetLatestVersion()
        => AtcApiNugetClientHelper.GetLatestVersionForPackageId("atc-coding-rules-updater");

    /// <summary>
    /// Text identifying the updater build that generated a block, for the temporary-suppressions
    /// header. Shared so the .editorconfig block and the standalone file cannot disagree.
    /// </summary>
    /// <remarks>
    /// Trimmed to three parts, since the fourth component is the git height and the version a user
    /// would install is the three-part package version.
    /// </remarks>
    public static string GetGeneratedByText()
    {
        var version = CliHelper.GetCurrentVersion();

        var versionText = version.Build >= 0
            ? version.ToString(3)
            : version.ToString();

        return $"generated by: atc-coding-rules-updater v{versionText}";
    }

    public static bool IsLatestVersion()
    {
        var currentVersion = CliHelper.GetCurrentVersion();
        if (currentVersion == new Version(1, 0, 0, 0))
        {
            return true;
        }

        var latestVersion = GetLatestVersion();
        return latestVersion is null || !latestVersion.GreaterThan(currentVersion);
    }

    public static void PrintUpdateInfoIfNeeded(ILogger logger)
    {
        if (IsLatestVersion())
        {
            return;
        }

        var currentVersion = CliHelper.GetCurrentVersion();
        var latestVersion = GetLatestVersion()!;
        logger.LogWarning($"Version {latestVersion} of ATC-Coding-Rules-Updater is available!");
        logger.LogWarning($"You are running version {currentVersion}");
        logger.LogWarning(string.Empty);
        logger.LogWarning("To update run the following command:");
        logger.LogWarning("   dotnet tool update --global atc-coding-rules-updater");
        logger.LogWarning(string.Empty);
    }
}