// ReSharper disable InvertIf
// ReSharper disable ReturnTypeCanBeEnumerable.Local
// ReSharper disable SuggestBaseTypeForParameter
// ReSharper disable ReplaceSubstringWithRangeIndexer
// ReSharper disable ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator
namespace Atc.CodingRules.Updater;

/// <summary>
/// Downloads .editorconfig files from the atc-coding-rules distribution and merges them with
/// any existing local .editorconfig, preserving the user's "Custom - …" sections.
/// </summary>
/// <remarks>
/// See <c>docs/architecture.md</c> for the full merge algorithm. The high-level rules, with the
/// <see cref="FileUpdateOutcome"/> each one reports:
/// <list type="bullet">
/// <item><description>Empty upstream content → don't overwrite (<see cref="FileUpdateOutcome.Skipped"/>).</description></item>
/// <item><description>Identical files → no write (<see cref="FileUpdateOutcome.Unchanged"/>).</description></item>
/// <item><description>Local missing → write upstream content (<see cref="FileUpdateOutcome.Created"/>).</description></item>
/// <item><description>Identical base section → no write (<see cref="FileUpdateOutcome.Unchanged"/>).</description></item>
/// <item><description>Otherwise rewrite the base section, preserving all <c># Custom -</c> sections from the local file (<see cref="FileUpdateOutcome.Updated"/>).</description></item>
/// </list>
/// <para>
/// <see cref="FileUpdateOutcome.Skipped"/> and <see cref="FileUpdateOutcome.Unchanged"/> are
/// deliberately distinct: the first means upstream gave us nothing to compare against, the second
/// means the local file is already correct. Only <c>Created</c> and <c>Updated</c> count as
/// changes for <c>--failOnChanges</c>.
/// </para>
/// </remarks>
public static class EditorConfigHelper
{
    /// <summary>The standard editor-config file name.</summary>
    public const string FileName = ".editorconfig";

    /// <summary>Visual section divider used in the generated .editorconfig.</summary>
    public const string SectionDivider = "##########################################";

    /// <summary>Prefix used by every preserved custom section header (<c># Custom - X</c>).</summary>
    public const string CustomSectionHeaderPrefix = "# Custom - ";

    /// <summary>Custom section name reserved for user-defined diagnostic suppressions.</summary>
    public const string CustomSectionHeaderCodeAnalyzersRulesSuffix = "Code Analyzers Rules";

    /// <summary>The default first line of an empty Custom - Code Analyzers Rules section.</summary>
    public const string CustomSectionFirstLine = "[*.{cs,csx,cake}]";

    /// <summary>Header used by the auto-generated temporary-suppression section (only present when <c>--useTemporarySuppressions</c> is on).</summary>
    public const string AutogeneratedCustomSectionHeaderPrefix = "# ATC temporary suppressions";

    /// <summary>
    /// Downloads the .editorconfig for <paramref name="urlPart"/> from the coding-rules distribution
    /// at <paramref name="rawCodingRulesDistribution"/> and merges it into <paramref name="path"/>.
    /// </summary>
    /// <param name="logger">Where progress is reported.</param>
    /// <param name="area">Short label used in error logs (e.g. <c>"root"</c>, <c>"src"</c>, <c>"ProjectFramework"</c>).</param>
    /// <param name="rawCodingRulesDistribution">Base raw URL pointing at the distribution folder for the chosen project target.</param>
    /// <param name="path">Local directory that should end up containing the .editorconfig.</param>
    /// <param name="urlPart">Sub-path appended to <paramref name="rawCodingRulesDistribution"/> (empty for root).</param>
    /// <param name="dryRun">When <c>true</c>, log what would change without writing any files.</param>
    /// <returns>What happened to the file, so callers can summarise the run.</returns>
    public static FileUpdateOutcome HandleFile(
        ILogger logger,
        string area,
        string rawCodingRulesDistribution,
        DirectoryInfo path,
        string urlPart,
        bool dryRun = false)
    {
        ArgumentNullException.ThrowIfNull(path);

        var descriptionPart = string.IsNullOrEmpty(urlPart)
            ? $"[yellow]root: [/]{FileName}"
            : $"[yellow]{urlPart}: [/]{FileName}";

        var file = new FileInfo(Path.Combine(path.FullName, FileName));

        var rawGitUrl = string.IsNullOrEmpty(urlPart)
            ? $"{rawCodingRulesDistribution}/{FileName}"
            : $"{rawCodingRulesDistribution}/{urlPart}/{FileName}";

        var displayName = rawGitUrl.Replace(Constants.GitRawContentUrl, Constants.GitHubPrefix, StringComparison.Ordinal);

        try
        {
            if (!Directory.Exists(file.Directory!.FullName))
            {
                if (dryRun)
                {
                    logger.LogInformation($"{EmojisConstants.FileCreated}   [dim](dry-run)[/] would create directory {file.Directory.FullName}");
                }
                else
                {
                    Directory.CreateDirectory(file.Directory.FullName);
                }
            }

            var contentGit = HttpClientHelper.GetAsString(logger, rawGitUrl, displayName).TrimEndForEmptyLines();
            var contentFile = FileHelper.ReadAllText(file);

            return HandleFile(logger, area, contentGit, contentFile, descriptionPart, file, dryRun);
        }
        catch (Exception ex)
        {
            logger.LogError($"{EmojisConstants.Error} {Markup.Escape(area)} - {Markup.Escape(ex.Message)}");
            throw;
        }
    }

    /// <summary>
    /// Lower-level overload used by <see cref="HandleFile(ILogger, string, string, DirectoryInfo, string, bool)"/>
    /// and unit tests: merges <paramref name="contentGit"/> into <paramref name="contentFile"/> and writes
    /// the result to <paramref name="file"/>, with the same merge rules described on the class.
    /// </summary>
    /// <returns>What happened to the file — see the rule list on the class for which path reports which outcome.</returns>
    public static FileUpdateOutcome HandleFile(
        ILogger logger,
        string area,
        string contentGit,
        string contentFile,
        string descriptionPart,
        FileInfo file,
        bool dryRun = false)
    {
        ArgumentNullException.ThrowIfNull(contentGit);
        ArgumentNullException.ThrowIfNull(file);

        try
        {
            if (string.IsNullOrEmpty(contentGit))
            {
                // Upstream returned an empty body (typically a 404 from atc-coding-rules
                // distribution for a not-yet-published path). Skip rather than overwrite the
                // user's local file with an empty merge result.
                logger.LogWarning($"{Emoji.Known.Warning}   {descriptionPart} skipped — upstream content is empty");
                return FileUpdateOutcome.Skipped;
            }

            if (FileHelper.AreFilesEqual(contentGit, contentFile))
            {
                logger.LogInformation($"{EmojisConstants.FileNotUpdated}   {descriptionPart} nothing to update");
                return FileUpdateOutcome.Unchanged;
            }

            if (string.IsNullOrEmpty(contentFile))
            {
                if (dryRun)
                {
                    logger.LogInformation($"{EmojisConstants.FileCreated}   [dim](dry-run)[/] would create {descriptionPart}");
                    return FileUpdateOutcome.Created;
                }

                FileHelper.CreateFile(logger, file, contentGit, descriptionPart);
                return FileUpdateOutcome.Created;
            }

            var contentGitBasePart = ExtractContentBasePart(contentGit);
            var contentFileBasePart = ExtractContentBasePart(contentFile);

            if (FileHelper.AreFilesEqual(contentGitBasePart, contentFileBasePart))
            {
                logger.LogInformation($"{EmojisConstants.FileNotUpdated}   {descriptionPart} nothing to update");
                return FileUpdateOutcome.Unchanged;
            }

            if (dryRun)
            {
                logger.LogInformation($"{EmojisConstants.FileUpdated}   [dim](dry-run)[/] would merge {descriptionPart}");
                return FileUpdateOutcome.Updated;
            }

            UpdateFile(logger, contentGit, contentFile, file, descriptionPart, contentGitBasePart);
            return FileUpdateOutcome.Updated;
        }
        catch (Exception ex)
        {
            logger.LogError($"{EmojisConstants.Error} {Markup.Escape(area)} - {Markup.Escape(ex.Message)}");
            throw;
        }
    }

    /// <summary>Reads the .editorconfig in <paramref name="path"/> as UTF-8 text.</summary>
    public static Task<string> ReadAllText(
        DirectoryInfo path,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(path);

        var file = new FileInfo(Path.Combine(path.FullName, FileName));
        return File.ReadAllTextAsync(file.FullName, Encoding.UTF8, cancellationToken);
    }

    /// <summary>Writes <paramref name="content"/> to the .editorconfig in <paramref name="path"/> as UTF-8.</summary>
    public static Task WriteAllText(
        DirectoryInfo path,
        string content,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(path);

        var file = new FileInfo(Path.Combine(path.FullName, FileName));
        return File.WriteAllTextAsync(file.FullName, content, Encoding.UTF8, cancellationToken);
    }

    /// <summary>
    /// Removes the auto-generated <c># ATC temporary suppressions</c> section from the root
    /// .editorconfig in <paramref name="projectPath"/>. No-op if the section is absent.
    /// </summary>
    public static Task UpdateRootFileRemoveCustomAtcAutogeneratedRuleSuppressions(
        DirectoryInfo projectPath)
    {
        ArgumentNullException.ThrowIfNull(projectPath);

        var rootEditorConfigFile = new FileInfo(Path.Combine(projectPath.FullName, FileName));
        var rawFileData = FileHelper.ReadAllText(rootEditorConfigFile);
        var lines = rawFileData.Split(FileHelper.LineBreaks, StringSplitOptions.None);
        var hasSection = lines.Any(x => x.Equals(AutogeneratedCustomSectionHeaderPrefix, StringComparison.Ordinal));
        if (!hasSection)
        {
            return Task.CompletedTask;
        }

        var linesBefore = ExtractBeforeCustomAutogeneratedRulesHeader(lines);
        var linesAfter = ExtractAfterCustomAutogeneratedRulesContent(lines);

        var linesToWrite = new List<string>();
        linesToWrite.AddRange(linesBefore);
        linesToWrite.AddRange(linesAfter);

        var contentToWrite = linesToWrite.TrimEndForEmptyValuesToString();
        return FileHelper.WriteAllTextAsync(rootEditorConfigFile, contentToWrite);
    }

    /// <summary>
    /// Appends an auto-generated <c># ATC temporary suppressions</c> section to the root
    /// .editorconfig in <paramref name="projectPath"/>, grouped by analyzer name.
    /// </summary>
    /// <param name="projectPath">Project root directory.</param>
    /// <param name="suppressionLinesPrAnalyzer">Tuples of (analyzer name, suppression lines).</param>
    public static Task UpdateRootFileAddCustomAtcAutogeneratedRuleSuppressions(
        DirectoryInfo projectPath,
        IList<Tuple<string, List<string>>> suppressionLinesPrAnalyzer)
    {
        ArgumentNullException.ThrowIfNull(projectPath);
        ArgumentNullException.ThrowIfNull(suppressionLinesPrAnalyzer);

        var rootEditorConfigFile = new FileInfo(Path.Combine(projectPath.FullName, FileName));
        var rawFileData = FileHelper.ReadAllText(rootEditorConfigFile);
        var lines = rawFileData
            .Split(FileHelper.LineBreaks, StringSplitOptions.None)
            .ToList();

        lines.Add(string.Empty);
        lines.Add(string.Empty);
        lines.Add(SectionDivider);
        lines.Add(AutogeneratedCustomSectionHeaderPrefix);
        lines.Add($"# generated @ {DateTime.Now:F}");
        lines.Add("# Please fix all generated temporary suppressions");
        lines.Add("# either by code changes or move the");
        lines.Add("# suppressions one by one to the relevant");
        lines.Add("# 'Custom - Code Analyzers Rules' section.");
        lines.Add(SectionDivider);
        lines.Add("[*.cs]");
        foreach (var (analyzerName, suppressionLines) in suppressionLinesPrAnalyzer)
        {
            lines.Add($"{Environment.NewLine}# {analyzerName}");
            lines.AddRange(suppressionLines);
        }

        var contentToWrite = lines.TrimEndForEmptyValuesToString();
        return FileHelper.WriteAllTextAsync(rootEditorConfigFile, contentToWrite);
    }

    private static void UpdateFile(
        ILogger logger,
        string contentGit,
        string contentFile,
        FileInfo file,
        string descriptionPart,
        string contentGitBasePart)
    {
        var contentGitCustomParts = ExtractContentCustomParts(contentGit);
        var contentFileCustomParts = ExtractContentCustomParts(contentFile);

        MergeCustomPartsToFileCustomParts(contentGitCustomParts, contentFileCustomParts);

        EnsureCustomSectionCodeAnalyzersRulesFirstLine(contentGit, contentFileCustomParts);

        var newContentFile = BuildNewContentFile(contentGitBasePart, contentFileCustomParts);

        File.WriteAllText(file.FullName, newContentFile);
        logger.LogInformation($"{EmojisConstants.FileUpdated}   {descriptionPart} files merged");

        var customLines = contentFileCustomParts
            .Find(x => x.Item1.Equals(CustomSectionHeaderCodeAnalyzersRulesSuffix, StringComparison.Ordinal))
            ?.Item2;

        if (customLines is not null)
        {
            var gitKeyValues = contentGit.GetDotnetDiagnosticSeverityKeyValues();
            var fileKeyValues = contentFile.GetDotnetDiagnosticSeverityKeyValues();
            var fileCustomKeyValues = customLines
                .ToArray()
                .GetDotnetDiagnosticSeverityKeyValues();

            LogSeverityDiffs(logger, gitKeyValues, fileKeyValues, fileCustomKeyValues, contentGit, newContentFile);
        }
    }

    private static void MergeCustomPartsToFileCustomParts(
        List<Tuple<string, List<string>>> contentGitCustomParts,
        List<Tuple<string, List<string>>> contentFileCustomParts)
    {
        foreach (var contentGitCustomPart in contentGitCustomParts)
        {
            if (!contentFileCustomParts.Any(x => x.Item1.Equals(contentGitCustomPart.Item1, StringComparison.Ordinal)))
            {
                if (contentFileCustomParts.Any(x =>
                        x.Item1.Equals(CustomSectionHeaderCodeAnalyzersRulesSuffix, StringComparison.Ordinal)))
                {
                    contentFileCustomParts.Insert(0, contentGitCustomPart);
                }
                else
                {
                    contentFileCustomParts.Add(contentGitCustomPart);
                }
            }
        }
    }

    private static void EnsureCustomSectionCodeAnalyzersRulesFirstLine(
        string contentGit,
        List<Tuple<string, List<string>>> contentFileCustomParts)
    {
        if (!contentGit.Contains("root = true", StringComparison.Ordinal))
        {
            return;
        }

        foreach (var (header, lines) in contentFileCustomParts)
        {
            if (header.Equals(CustomSectionHeaderCodeAnalyzersRulesSuffix, StringComparison.Ordinal) &&
                lines.Count == 0)
            {
                lines.Insert(0, CustomSectionFirstLine);
            }
        }
    }

    private static string BuildNewContentFile(
        string contentGitBasePart,
        List<Tuple<string, List<string>>> contentFileCustomParts)
    {
        var sbNewContentFile = new StringBuilder();
        sbNewContentFile.Append(contentGitBasePart);
        if (contentFileCustomParts.Count > 0)
        {
            sbNewContentFile.AppendLine();
        }

        foreach (var (header, lines) in contentFileCustomParts)
        {
            sbNewContentFile.AppendLine();
            sbNewContentFile.AppendLine();
            sbNewContentFile.AppendLine(SectionDivider);
            sbNewContentFile.AppendLine(CustomSectionHeaderPrefix + header);
            sbNewContentFile.AppendLine(SectionDivider);
            foreach (var line in lines)
            {
                sbNewContentFile.AppendLine(line);
            }
        }

        var newContentFile = sbNewContentFile
            .ToString()
            .TrimEndForEmptyLines();

        return newContentFile;
    }

    private static string ExtractContentBasePart(string content)
    {
        var lines = content.Split(FileHelper.LineBreaks, StringSplitOptions.None);

        var sb = new StringBuilder();
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            if (line.Equals(SectionDivider, StringComparison.Ordinal) &&
                i + 1 < lines.Length)
            {
                var nextLine = lines[i + 1];
                if (nextLine.StartsWith(CustomSectionHeaderPrefix, StringComparison.Ordinal))
                {
                    return sb
                        .ToString()
                        .TrimEndForEmptyLines();
                }
            }

            sb.AppendLine(line);
        }

        return sb
            .ToString()
            .TrimEndForEmptyLines();
    }

    private static List<Tuple<string, List<string>>> ExtractContentCustomParts(
        string content)
    {
        var customParts = new List<Tuple<string, List<string>>>();

        var lines = content.Split(FileHelper.LineBreaks, StringSplitOptions.None);

        var workingOnCustomHeader = string.Empty;
        var workingOnCustomLines = new List<string>();
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            if (line.Equals(SectionDivider, StringComparison.Ordinal) &&
                i + 1 < lines.Length)
            {
                var nextLine = lines[i + 1];
                if (nextLine.StartsWith(CustomSectionHeaderPrefix, StringComparison.Ordinal))
                {
                    if (workingOnCustomHeader.Length != 0)
                    {
                        workingOnCustomLines.TrimEndForEmptyValues();
                        customParts.Add(new Tuple<string, List<string>>(workingOnCustomHeader, workingOnCustomLines));
                    }

                    workingOnCustomHeader = nextLine
                        .Substring(CustomSectionHeaderPrefix.Length)
                        .Trim();

                    workingOnCustomLines = [];
                }
            }

            if (workingOnCustomHeader.Length > 0 &&
                !(line.Equals(SectionDivider, StringComparison.Ordinal) ||
                  line.StartsWith(CustomSectionHeaderPrefix, StringComparison.Ordinal)))
            {
                workingOnCustomLines.Add(line);
            }
        }

        if (workingOnCustomHeader.Length > 0 &&
            !customParts.Any(x => x.Item1.Equals(workingOnCustomHeader, StringComparison.Ordinal)))
        {
            workingOnCustomLines.TrimEndForEmptyValues();
            customParts.Add(new Tuple<string, List<string>>(workingOnCustomHeader, workingOnCustomLines));
        }

        return customParts;
    }

    private static string[] ExtractBeforeCustomAutogeneratedRulesHeader(
        IEnumerable<string> lines)
    {
        var result = lines
            .TakeWhile(line => !line.Equals(AutogeneratedCustomSectionHeaderPrefix, StringComparison.Ordinal))
            .ToList();

        if (result.Count > 0 &&
            result[^1].Equals(SectionDivider, StringComparison.Ordinal))
        {
            result.RemoveAt(result.Count - 1);
        }

        return result.ToArray();
    }

    private static string[] ExtractAfterCustomAutogeneratedRulesContent(
        IEnumerable<string> lines)
    {
        var result = new List<string>();
        var foundHeader = false;
        var foundSectionDividerStart = false;
        var foundSectionDividerEnd = false;
        foreach (var line in lines)
        {
            switch (foundHeader)
            {
                case false when line.Equals(AutogeneratedCustomSectionHeaderPrefix, StringComparison.Ordinal):
                    foundHeader = true;
                    continue;
                case false:
                    continue;
            }

            if (line.Equals(SectionDivider, StringComparison.Ordinal))
            {
                if (!foundSectionDividerStart)
                {
                    foundSectionDividerStart = true;
                    continue;
                }

                if (!foundSectionDividerEnd)
                {
                    foundSectionDividerEnd = true;
                }
            }

            if (foundSectionDividerStart && foundSectionDividerEnd)
            {
                result.Add(line);
            }
        }

        return result.ToArray();
    }

    /// <summary>
    /// Compares dotnet_diagnostic.X.severity entries between the git base section and the user's
    /// custom section after merge.
    /// </summary>
    /// <remarks>
    /// When the same key exists in both, the custom-section value wins by design — that is the
    /// user's intentional override. We surface a warning so that a user who *thought* they were
    /// inheriting the upstream default can spot and remove the redundant override; we do not
    /// silently strip either entry, since either might be intentional.
    /// </remarks>
    private static void LogSeverityDiffs(
        ILogger logger,
        IEnumerable<KeyValueItem> gitKeyValues,
        IReadOnlyCollection<KeyValueItem> fileKeyValues,
        IReadOnlyCollection<KeyValueItem> fileCustomKeyValues,
        string contentGit,
        string contentFile)
    {
        var gitLines = contentGit.Split(FileHelper.LineBreaks, StringSplitOptions.None);
        var fileLines = contentFile.Split(FileHelper.LineBreaks, StringSplitOptions.None);

        foreach (var gitKeyValue in gitKeyValues)
        {
            var key = gitKeyValue.Key;
            var item = fileCustomKeyValues.FirstOrDefault(x => x.Key.Equals(key, StringComparison.Ordinal));
            if (item != null)
            {
                // Same key in both git base and the user's custom section.
                // The custom-section entry wins; the duplicate warning lets the user
                // remove their override if they wanted the upstream default.
                var gitLineNumber = GetLineNumberForwardSearch(gitLines, key);
                var fileLineNumber = GetLineNumberReverseSearch(fileLines, item);

                logger.LogWarning($"{AppEmojisConstants.DuplicateKey}   Duplicate key: {Markup.Escape(key)} — custom section overrides upstream default; remove your custom entry to inherit it.");
                logger.LogWarning($"{FormattableString.Invariant($"     -- GitHub section (line {gitLineNumber:0000}): ")}{Markup.Escape(gitKeyValue.Value.Trim())}");
                logger.LogWarning($"{FormattableString.Invariant($"     -- Custom section (line {fileLineNumber:0000}): ")}{Markup.Escape(item.Value.Trim())}");
            }
            else if (!fileKeyValues.Any(x => x.Key.Equals(key, StringComparison.Ordinal)))
            {
                // Key is new in upstream and not yet in the user's file.
                logger.LogDebug($"     - New key/value - {Markup.Escape(key)}={Markup.Escape(gitKeyValue.Value)}");
            }
        }
    }

    private static int GetLineNumberForwardSearch(
        IReadOnlyList<string> lines,
        string key)
    {
        for (var i = 0; i < lines.Count; i++)
        {
            if (lines[i].StartsWith(key, StringComparison.Ordinal))
            {
                return i + 1;
            }
        }

        return -1;
    }

    private static int GetLineNumberReverseSearch(
        IReadOnlyList<string> lines,
        KeyValueItem keyValueItem)
    {
        for (var i = lines.Count - 1; i >= 0; i--)
        {
            if (lines[i].Equals($"{keyValueItem.Key}={keyValueItem.Value}", StringComparison.Ordinal))
            {
                return i + 1;
            }
        }

        return -1;
    }
}