name: "Pre-Integration"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  dotnet-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚙️ Setup dotnet 10.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: 🧹 Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: 🔁 Restore packages
        run: dotnet restore

      - name: 🛠️ Building library in release mode
        run: dotnet build -c Release --no-restore

  dotnet-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - dotnet-build
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚙️ Setup dotnet 10.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: 🔁 Restore packages
        run: dotnet restore

      - name: 🛠️ Build
        run: dotnet build -c Release --no-restore /p:UseSourceLink=true

      - name: 🧪 Run unit tests
        run: dotnet test -c Release --no-build --filter-query "/[category!=integration]" --ignore-exit-code 8